### ISSUE TITLE
literature review

### ISSUE THREAD

**Issue by akaanuzman** [akaanuzman/digital_order_system#10]
further article searches for literature review

**Comment by alperenakarslan** [comment]
sadasdsad

**Comment by akaanuzman** [comment]
Doc link: https://docs.google.com/document/d/1UUTaY4gC3QpCYZKe02AU5oyjrJDOOimWfG05jE5-XXs/edit

**Comment by alperenakarslan** [comment]
https://jotags.org/2022/vol10_Issue2_article2.pdf

**Comment by akaanuzman** [comment]
https://www.mdpi.com/2071-1050/13/1/95

**Comment by akaanuzman** [comment]
https://www.sciencedirect.com/science/article/abs/pii/S0306457317309081
tam isteğimiz konuyu ele almışlar

**Comment by akaanuzman** [comment]
https://openaccess.thecvf.com/content_cvpr_2017_workshops/w26/papers/Ventura_Interpreting_CNN_Models_CVPR_2017_paper.pdf
cnn geldi yine gayış paket

**Comment by alperenakarslan** [comment]
https://link.springer.com/chapter/10.1007/978-3-319-49409-8_25

bulduğuma yapışıyorum amk farklı bakış açılarına falan baktık deriz hem

**Comment by alperenakarslan** [comment]
https://openaccess.thecvf.com/content_cvpr_2018_workshops/w48/html/Dotti_Behavior_and_Personality_CVPR_2018_paper.html
bidene de bunu buldum iyisinden benzerlik var

**Comment by alperenakarslan** [comment]
https://link.springer.com/article/10.1007/s11263-020-01309-y
bir de cr net diyor kanks

**Comment by alperenakarslan** [comment]
https://ieeexplore.ieee.org/abstract/document/9537374
bir de bu vardır
